name: Working with scverse objects in backed mode
description: |
  In this tutorial, we demonstrate working with scverse data objects
  without loading full datasets. (AnnData and MuData are saved as .h5ad and .h5mu files)
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/scverse_data_backed.html#working-with-scverse-objects-in-backed-mode
primary_category: Data structures
image: icon.png
tags:
  - data structures
packages:
  - anndata
  - mudata
  - scanpy
authors:
  - emdann
