name: RNA velocity
description: |
  This tutorial guides you through how RNA velocity can be inferred from single cell RNA-seq data
  using scVelo.
link: https://scvelo.readthedocs.io/en/stable/getting_started.html
image: icon.png
primary_category: scRNA-seq
tags:
  - preprocessing
  - RNA velocity
  - visualization
packages:
  - anndata
  - scanpy
authors:
  - VolkerBergen
  - WeilerP
  - stefanpeidli
  - Marius1311
