name: Single-cell T-cell receptor analysis with scirpy
description: |
  QC scTCR-seq data, define clonotypes, cluster receptors by sequence similarity and compare repertoires.
link: https://scirpy.scverse.org/en/latest/tutorials/tutorial_3k_tcr.html
primary_category: Adaptive immune cell receptor
order: 10
image: icon.svg
tags:
  - quality control
  - preprocessing
  - visualization
  - multimodal
packages:
  - scirpy
  - muon
  - mudata
  - anndata
authors:
  - grst
