name: Interoperability
description: |
  This document lists resources for conversion to other data formats and programming
  languages, e.g. R, Julia, ...
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/scverse_data_interoperability.html
image: icon.png
primary_category: Tips & Tricks
order: 20
tags:
  - interoperability
packages:
  - anndata
  - mudata
authors:
  - emdann
