name: Interoperability
description: |
  Resources for converting scverse data to other formats and languages, such as R and Julia.
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/scverse_data_interoperability.html
image: icon.png
primary_category: Tips & Tricks
order: 20
tags:
  - interoperability
packages:
  - anndata
  - mudata
authors:
  - emdann
