name: Interoperability
description: |
    This document lists resources for conversion to other data formats and programming
    languages, e.g. R, Julia, ...
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/scverse_data_interoperability.html
image: icon.webp
primary_category: Tips & Tricks
tags:
    - interoperability
packages:
    - anndata
    - mudata
authors:
    - emdann
