name: Concatenation of multimodal data
description: |
    This tutorial shows how you can concatenate 2 MuData objects that may represent complementary 
    slices of the same dataset or 2 modalities into one AnnData.
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/tutorial_concatenation_anndata_mudata.html
image: icon.png
primary_category: scRNA-seq
tags:
    - concatenation
    - data structures
packages:
    - anndata
    - scanpy
    - mudata
authors:
    - ivirshup
    - dbdimitrov
    - AnnaChristina
    - Hrovatin
