name: Axes in AnnData and MuData
description: |
  Operations on independent AnnData objects, and how several processing workflows can live in one MuData object.
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/tutorial_axes_anndata_mudata.html
primary_category: Data structures
order: 20
image: icon.svg
tags:
  - data structures
packages:
  - anndata
authors:
  - bio-la
