name: Spatial clustering of spacial transcriptomics data with CellCharter
description: |
  This tutorial demonstrate how to use CellCharter to cluster spatial transcriptomics data, obtained with the CosMx technology from Nanostring.
  This method can also be used for spatial proteomics data.
link: https://cellcharter.readthedocs.io/en/latest/notebooks/cosmx_human_nsclc.html
image: icon.png
primary_category: Spatial
order: 20
tags:
  - compositional analysis
packages:
  - CellCharter
  - squidpy
  - scvi
  - scanpy
  - anndata
authors:
  - marcovarrone
  - grst
