name: Plotting in scanpy
description: |
  Visualization with scanpy, covering embeddings, marker genes and differentially expressed genes.
link: https://scanpy.readthedocs.io/en/stable/tutorials/plotting/core.html
image: icon.png
primary_category: Tips & Tricks
order: 10
tags:
  - visualization
packages:
  - scanpy
authors:
  - fidelram
