name: Pseudo-bulk differential expression and functional analysis
description: |
    This notebook showcases decoupler for pathway and TF enrichment on ~5k
    Blood myeloid cells from healthy and COVID-19 infected patients.
link: https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html
image: icon.png
primary_category: scRNA-seq
tags:
    - differential expression
    - functional analysis
packages:
    - decoupler
    - scanpy
authors:
    - PauBadiaM
