name: Pseudo-bulk differential expression and functional analysis
description: |
  Pathway and TF enrichment on ~5k blood myeloid cells from healthy and COVID-19 patients.
link: https://decoupler.readthedocs.io/en/latest/notebooks/scell/rna_psbk.html
image: icon.png
primary_category: scRNA-seq
order: 30
tags:
  - differential expression
  - functional analysis
packages:
  - decoupler
  - scanpy
authors:
  - PauBadiaM
