name: Standard scATAC-seq pipeline with SnapATAC2
description: |
  From fragment file to annotated clusters on 5k PBMCs: quality control, dimension reduction, clustering.
link: https://snapatac2.scverse.org/tutorials/pbmc.html
image: icon.svg
primary_category: ATAC-seq
order: 5
modality:
  - ATAC
tags:
  - quality control
  - preprocessing
  - cell-type annotation
  - visualization
packages:
  - snapatac2
  - anndata
authors:
  - kaizhang
