name: CITE-seq integration
description: |
    These notebooks cover different CITE-seq datasets for analysis of PBMCs
    showcasing dsb normalisation and data integration with MOFA+ and
    calculating weighted nearest neighbours to demonstrate how to
    handle multiple multimodal embeddings.
link: https://muon-tutorials.readthedocs.io/en/latest/cite-seq/index.html
image: icon.png
primary_category: Surface proteins
tags:
    - multimodal
    - data integration
packages:
    - scanpy
    - muon
    - mofax
authors:
    - gtca
