name: B-cell receptor analysis with scirpy
description: |
  Quality control, clonotype definition, somatic hypermutation and isotype usage in 5k B cells.
link: https://scirpy.scverse.org/en/latest/tutorials/tutorial_5k_bcr.html
image: icon.svg
primary_category: Adaptive immune cell receptor
order: 20
modality:
  - AIRR
  - RNA
tags:
  - quality control
  - preprocessing
  - visualization
packages:
  - scirpy
  - mudata
  - anndata
authors:
  - grst
