name: Processing chromatin accessibility
description: |
    This chapter shows multimodal single-cell gene expression and
    chromatin accessibility analysis. In this notebook, scATAC-seq
    data processing is described.
link: https://muon-tutorials.readthedocs.io/en/latest/single-cell-rna-atac/pbmc10k/2-Chromatin-Accessibility-Processing.html
image: icon.png
primary_category: ATAC
tags:
    - preprocessing
    - multimodal
packages:
    - anndata
    - scanpy
    - muon
authors:
    - gtca
