name: Processing chromatin accessibility
description: |
  Process scATAC-seq data as one half of a multimodal gene expression and chromatin accessibility analysis.
link: https://muon-tutorials.readthedocs.io/en/latest/single-cell-rna-atac/pbmc10k/2-Chromatin-Accessibility-Processing.html
image: icon.png
primary_category: ATAC-seq
order: 10
tags:
  - preprocessing
  - multimodal
packages:
  - anndata
  - scanpy
  - muon
authors:
  - gtca
