name: Processing chromatin accessibility
description: |
  Chromatin accessibility processing in a joint RNA and ATAC analysis of 10k PBMCs.
link: https://muon-tutorials.readthedocs.io/en/latest/single-cell-rna-atac/pbmc10k/2-Chromatin-Accessibility-Processing.html
image: icon.png
primary_category: ATAC-seq
order: 10
tags:
  - preprocessing
  - multimodal
packages:
  - anndata
  - scanpy
  - muon
authors:
  - gtca
