name: Single-cell enrichment analysis
description: |
  Score transcription factor and pathway activities in individual cells with
  decoupler, and compare the resulting activities across cell types.
link: https://decoupler.readthedocs.io/en/latest/notebooks/scell/rna_sc.html
image: icon.png
primary_category: scRNA-seq
order: 25
modality:
  - RNA
tags:
  - functional analysis
  - visualization
packages:
  - decoupler
  - scanpy
  - anndata
authors:
  - PauBadiaM
