name: Compositional analysis
description: |
  This tutorial introduces compositional analysis at cell identity
  cluster level, based on known cell types or states affected by
  perturbations.
link: https://www.sc-best-practices.org/conditions/compositional.html
image: icon.png
primary_category: scRNA-seq
tags:
  - compositional analysis
packages:
  - scanpy
  - tensorflow
authors:
  - johannesostner
  - emdann
  - Zethson
  - alitinet
