name: Concatenation
description: |
  Concatenate objects while keeping all sub-elements of each, stacked in an ordered way.
link: https://anndata.readthedocs.io/en/stable/tutorials/concatenation.html
image: icon.png
primary_category: Data structures
order: 30
tags:
  - concatenation
packages:
  - anndata
  - scanpy
  - scipy
authors:
  - ivirshup
