name: Cell-cell communication with LIANA+
description: |
  Infer ligand-receptor interactions between cell types and aggregate the methods into a consensus ranking.
link: https://liana-py.readthedocs.io/en/latest/notebooks/basic_usage.html
image: icon.png
primary_category: Cell-cell communication
order: 10
modality:
  - RNA
tags:
  - functional analysis
  - visualization
packages:
  - liana
  - scanpy
  - anndata
authors:
  - dbdimitrov
