name: Getting started with AnnData
description: |
  This tutorial helps you to explore the structure and content of single-cell
  data analysis results in a *.h5ad file using AnnData, Scanpy, and Python.
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/anndata_getting_started.html
image: icon.svg
primary_category: Data structures
tags:
  - data structures
packages:
  - anndata
authors:
  - jlause
