name: Getting started with AnnData
description: |
  Explore the structure and content of single-cell analysis results stored in an .h5ad file.
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/anndata_getting_started.html
image: icon.svg
primary_category: Data structures
order: 10
tags:
  - data structures
packages:
  - anndata
authors:
  - jlause
