name: Preprocessing, clustering and cell-type annotation
description: |
  This fundamental tutorial covers common analysis steps: quality control,
  normalization, feature selection, dimensionality reduction, clustering,
  and cell-type annotation.
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/basic-scrna-tutorial.html
image: icon.webp
primary_category: scRNA-seq
order: 10
tags:
  - preprocessing
  - cell-type annotation
  - quality control
  - visualization
packages:
  - anndata
  - scanpy
  - celltypist
  - decoupler
authors:
  - ivirshup
  - dbdimitrov
  - AnnaChristina
  - Hrovatin
