name: Spatial analysis with squidpy
description: |
  Analyse transcriptomics data with spatial resolution using squidpy.
link: https://squidpy.readthedocs.io/en/latest/notebooks/tutorials/tutorial_vizgen_mouse_liver.html
image: icon.png
primary_category: Spatial
order: 10
tags:
  - preprocessing
  - visualization
packages:
  - squidpy
authors:
  - giovp
