name: Spatial analysis at subcellular resolution
description: |
    This tutorial shows how to use bentotools to study
    gene expression at subcellular resolution.
link: https://bento-tools.readthedocs.io/en/latest/index.html
image: icon.png
primary_category: Spatial
tags:
    - preprocessing
    - visualization
packages:
    - bento-tools
authors:
    - ckmah
