name: Perturbation modeling
description: |
  Augur to identify affected cell types, scGen to predict transcriptional response, Mixscape for CRISPR sensitivity.
link: https://www.sc-best-practices.org/conditions/perturbation_modeling.html
image: icon.png
primary_category: scRNA-seq
order: 60
tags:
  - perturbation
packages:
  - pertpy
  - scanpy
authors:
  - Zethson
  - M0hammadL
