name: Joint analysis of paired and unpaired multiomic data with MultiVI
description: |
    This tutorial walks through how to read multiomic data, create a joint
    object with paired and unpaired data, set-up and train a MultiVI model,
    visualize the resulting latent space, and run differential analyses.
link: https://docs.scvi-tools.org/en/stable/tutorials/notebooks/MultiVI_tutorial.html
image: icon.png
primary_category: ATAC-seq
tags:
    - preprocessing
    - visualization
    - differential expression
packages:
    - scanpy
    - scvi
authors:
    - adamgayoso
    - galenxing
    - romain-lopez
    - Edouard360
    - martinkim0
