name: Execute notebooks
on:
    pull_request:
        branches: [main]
jobs:
    runnbs:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -el {0}
        steps:
            - uses: actions/checkout@v2
            - name: Cache conda
              uses: actions/cache@v2
              env:
                  # Increase this value to reset cache if env file has not changed
                  CACHE_NUMBER: 0
              with:
                  path: ~/conda_pkgs_dir
                  key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
            - name: Cache notebooks
              uses: actions/cache@v2
              env:
                  # Increase this value to reset cache if env file has not changed
                  CACHE_NUMBER: 0
              with:
                  path: .jupyter_cache
                  key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
            - uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: tutorials
                  channel-priority: strict
                  environment-file: environment.yml
                  miniforge-variant: Mambaforge
                  miniforge-version: latest
                  use-mamba: true
                  use-only-tar-bz2: true # This needs to be set for caching to work properly!

            # - name: Setup tmate session
            #   uses: mxschmitt/action-tmate@v3

            - name: execute notebooks
              run: |
                  yes | jcache notebook add docs/notebooks/*.ipynb
                  jcache project execute

            - uses: stefanzweifel/git-auto-commit-action@v4
